### ISSUE TITLE
No longer working with optifine

### ISSUE THREAD

**Issue by adamwbb** [eccentricdevotion/TARDIS-MCP#3]
These textures used to work with optifine now they dont.
Minecraft 1.8.8 - OptiFine_1.8.8_HD_U_G7
 TARDIS v3.4.2 - Spigot 1.8.8

**Comment by eccentricdevotion** [comment]
It's called TARDIS-MCP for a reason - the MCP stands for MCPatcher - which is what it supports. Optifine does not have all of MCPatcher's features and never has.

**Comment by ThemInspectors** [comment]
can you use optifine? can you make a Texture Pack for optifine?

**Comment by eccentricdevotion** [comment]
Suggest you actually look at the recent commits before asking next time... https://github.com/eccentricdevotion/TARDIS-MCP/commits/master

**Comment by ThemInspectors** [comment]
Maybe update the README.md ? it's missleading

**Comment by eccentricdevotion** [comment]
MCPatcher is still the preferred mod, OptiFine seems pretty sketchy at times (it doesn't work at all for the TARDISWeepingAngel pack)
