### ISSUE TITLE
Invisible pumpkins in inventory

### ISSUE THREAD

**Issue by Squawkers13** [eccentricdevotion/TARDIS-MCP#5]
I'm running Minecraft 1.11.2 + Optifine and a resource pack that includes the TARDIS and TWA textures.

Pumpkins show as invisible in the inventory, and use the default vanilla texture (overriding a resource pack I have applied underneath) when placed.

**Comment by eccentricdevotion** [comment]
Waiting for LibsDisguises to be fixed - https://github.com/libraryaddict/LibsDisguises/issues/187

And: https://dev.bukkit.org/projects/tardis?comment=8051

**Comment by eccentricdevotion** [comment]
My placed pumpkins currently use my custom Bromley Massive texture not default...

**Comment by eccentricdevotion** [comment]
LibsDisguises has been fixed, though you'll need to compile the plugin yourself as the Jenkins builds aren't working...
